services:
  app:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    build:
      context: ./MealPlanner-backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=webshop;User=root;Password=123123;
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: '123123'
      MYSQL_DATABASE: webshop
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
