name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build
    - name: Test the application with the dotnet CLI
      run: dotnet test

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
    - name: Test
      run: "echo build was successful"
