name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.8'

    - name: Build and Run with Docker Compose
      run: |
        docker-compose up --build -d
        docker-compose exec app dotnet test
        docker-compose down

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Test
      run: "echo build was successful"
